// Canonical value -> phrases recruiters actually type. Matching is case-insensitive
// and word-bounded (see interpreter.js), so "react" doesn't match "reactive".

export const TITLES = {
  'Frontend Engineer': ['frontend engineer', 'front-end engineer', 'front end engineer', 'frontend developer', 'front-end developer', 'front end developer', 'frontend dev', 'ui engineer', 'react developer', 'react engineer'],
  'Backend Engineer': ['backend engineer', 'back-end engineer', 'back end engineer', 'backend developer', 'back-end developer', 'api engineer', 'node developer', 'node.js developer'],
  'Full Stack Engineer': ['full stack engineer', 'full-stack engineer', 'fullstack engineer', 'full stack developer', 'full-stack developer', 'fullstack developer', 'full stack', 'fullstack'],
  'Mobile Engineer': ['mobile engineer', 'mobile developer', 'ios developer', 'ios engineer', 'android developer', 'android engineer', 'react native developer'],
  'Data Engineer': ['data engineer', 'etl developer', 'big data engineer'],
  'Data Scientist': ['data scientist', 'data science'],
  'Machine Learning Engineer': ['machine learning engineer', 'ml engineer', 'ai engineer', 'mlops engineer'],
  'DevOps Engineer': ['devops engineer', 'devops', 'site reliability engineer', 'sre', 'platform engineer', 'cloud engineer'],
  'QA Engineer': ['qa engineer', 'test engineer', 'sdet', 'quality engineer', 'automation tester', 'qa'],
  'Product Manager': ['product manager', 'product owner'],
  'Product Designer': ['product designer', 'ux designer', 'ui designer', 'ui/ux designer', 'ux/ui designer'],
};

export const SKILLS = {
  JavaScript: ['javascript', 'js', 'es6'],
  TypeScript: ['typescript'],
  React: ['react', 'react.js', 'reactjs'],
  'Next.js': ['next.js', 'nextjs'],
  Redux: ['redux'],
  Vue: ['vue', 'vue.js', 'vuejs'],
  Angular: ['angular'],
  CSS: ['css', 'css3', 'scss', 'sass'],
  Tailwind: ['tailwind', 'tailwindcss'],
  'Node.js': ['node', 'node.js', 'nodejs'],
  Express: ['express', 'express.js'],
  GraphQL: ['graphql'],
  Python: ['python'],
  Django: ['django'],
  Java: ['java'],
  Spring: ['spring', 'spring boot'],
  Go: ['golang'],
  'C#': ['c#', '.net', 'dotnet'],
  SQL: ['sql'],
  PostgreSQL: ['postgres', 'postgresql'],
  MongoDB: ['mongodb', 'mongo'],
  Redis: ['redis'],
  Kafka: ['kafka'],
  AWS: ['aws', 'amazon web services'],
  GCP: ['gcp', 'google cloud'],
  Azure: ['azure'],
  Docker: ['docker'],
  Kubernetes: ['kubernetes', 'k8s'],
  Terraform: ['terraform'],
  Spark: ['spark', 'pyspark'],
  Airflow: ['airflow'],
  PyTorch: ['pytorch'],
  TensorFlow: ['tensorflow'],
  Swift: ['swift'],
  Kotlin: ['kotlin'],
  'React Native': ['react native'],
  Cypress: ['cypress'],
  Selenium: ['selenium'],
  Playwright: ['playwright'],
  Figma: ['figma'],
  'Product Strategy': ['product strategy', 'roadmapping', 'roadmap'],
};

/** label -> { kind: 'city' | 'country' | 'remote', country?, aliases } */
export const LOCATIONS = {
  'New York': { kind: 'city', country: 'United States', aliases: ['new york', 'nyc', 'new york city'] },
  'San Francisco': { kind: 'city', country: 'United States', aliases: ['san francisco', 'sf', 'bay area'] },
  Austin: { kind: 'city', country: 'United States', aliases: ['austin'] },
  Seattle: { kind: 'city', country: 'United States', aliases: ['seattle'] },
  Boston: { kind: 'city', country: 'United States', aliases: ['boston'] },
  Chicago: { kind: 'city', country: 'United States', aliases: ['chicago'] },
  Denver: { kind: 'city', country: 'United States', aliases: ['denver'] },
  Toronto: { kind: 'city', country: 'Canada', aliases: ['toronto'] },
  London: { kind: 'city', country: 'United Kingdom', aliases: ['london'] },
  Berlin: { kind: 'city', country: 'Germany', aliases: ['berlin'] },
  Bengaluru: { kind: 'city', country: 'India', aliases: ['bengaluru', 'bangalore'] },
  Hyderabad: { kind: 'city', country: 'India', aliases: ['hyderabad'] },
  Pune: { kind: 'city', country: 'India', aliases: ['pune'] },
  'United States': { kind: 'country', aliases: ['united states', 'usa', 'u.s.', 'us based', 'america'] },
  Canada: { kind: 'country', aliases: ['canada'] },
  'United Kingdom': { kind: 'country', aliases: ['united kingdom', 'uk', 'england'] },
  Germany: { kind: 'country', aliases: ['germany'] },
  India: { kind: 'country', aliases: ['india'] },
  Remote: { kind: 'remote', aliases: ['remote', 'work from home', 'wfh', 'anywhere remote'] },
};

export const COMPANIES = {
  Google: ['google', 'alphabet'],
  Microsoft: ['microsoft'],
  Amazon: ['amazon', 'aws'],
  Meta: ['meta', 'facebook'],
  Apple: ['apple'],
  Netflix: ['netflix'],
  Stripe: ['stripe'],
  Shopify: ['shopify'],
  Airbnb: ['airbnb'],
  Uber: ['uber'],
  Atlassian: ['atlassian'],
  Salesforce: ['salesforce'],
  Adobe: ['adobe'],
  Infosys: ['infosys'],
  TCS: ['tcs', 'tata consultancy'],
  Accenture: ['accenture'],
  Flipkart: ['flipkart'],
  Swiggy: ['swiggy'],
};

// Smaller (fictional) employers so not every profile is a big-tech one.
export const STARTUPS = ['Brightloop', 'Nimbus Labs', 'Quillstack', 'Harbor Health', 'Lumen Pay', 'Fieldnote', 'Cobalt AI', 'Tandem Freight'];

export const SENIORITY = {
  junior: ['junior', 'jr', 'entry level', 'entry-level', 'graduate', 'fresher'],
  mid: ['mid level', 'mid-level', 'midlevel', 'intermediate'],
  senior: ['senior', 'sr'],
  lead: ['lead', 'staff', 'principal', 'tech lead', 'architect'],
};
